# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{14}}
      uses: actions/setup-node@v1
      with:
        node-version: '14'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build cfs_applica
      run: npm run build --prod
      
    - name: app_deploy
    - uses: actions/checkout@v1
      with:
          run_lint: true
          github_access_token: ${{ secrets.ACCESS_TOKEN }}
          build_configuration: dist/cfs
          base_href: https://redmindtech.github.io/cfs-app/
          deploy_branch: gh-pages 
          angular_dist_build_folder: redmindtech/dist/cfs # The folder the action should deploy.
         
 
